services:

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - MRTA_ENV=dev
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    depends_on:
      - ollama

  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - MRTA_ENV=dev
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    depends_on:
      - api

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama

volumes:
  ollama_models:
